In [3]:
import numpy as np 
import pandas as pd

In [4]:
df = pd.read_csv('train.csv')

In [5]:
df.head()

   label  pixel0  pixel1  pixel2  ...  pixel780  pixel781  pixel782  pixel783
0      1       0       0       0  ...         0         0         0         0
1      0       0       0       0  ...         0         0         0         0
2      1       0       0       0  ...         0         0         0         0
3      4       0       0       0  ...         0         0         0         0
4      0       0       0       0  ...         0         0         0         0

[5 rows x 785 columns]

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['label'], axis=1), df['label'], test_size=0.2, random_state=2)

In [8]:

clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

clf1.fit(X_train, y_train)
clf2.fit(X_train, y_train)

y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

c:\Users\SUNIL\Anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [9]:
from sklearn.metrics import accuracy_score, confusion_matrix
print(f'Accuracy of {clf1.__class__.__name__}: {accuracy_score(y_test, y_pred1)}')
print(f'Accuracy of {clf2.__class__.__name__}: {accuracy_score(y_test, y_pred2)}')

Accuracy of LogisticRegression: 0.9145238095238095
Accuracy of DecisionTreeClassifier: 0.8503571428571428

In [10]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test, y_pred1),columns=list(range(0,10)))

Logistic Regression Confusion Matrix

     0    1    2    3    4    5    6    7    8    9
0  791    0    1    0    1    9   11    1    6    1
1    0  938    2    4    0    3    0    3   12    0
2    2    9  745   16    9    4   13   13   15    3
3    1    4   19  763    0   36    5    5   20   11
4    2    5    4    0  804    1    7    3    9   21
5    9    3    4   23   10  610   15   10   34   11
6   12    4   12    1    7    8  789    0    5    1
7    3    2   13    6    4    2    0  812    2   29
8   11   12   13   18    1   21    6    6  694   11
9    3    6    2   14   25    4    0   37    7  736

In [11]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test, y_pred2),columns=list(range(0,10)))

Decision Tree Confusion Matrix

     0    1    2    3    4    5    6    7    8    9
0  759    0    7    8    2   15   10    3   11    6
1    0  901   13    6   10    4    5    7   14    2
2   10   16  671   36   16   12   17   23   20    8
3    7   10   30  686    7   44    9   16   31   24
4    8    4    8    8  728   13   12   14   19   42
5   13    6   10   38   14  576   24   10   24   14
6   10    1    9    8   11   23  759    0   13    5
7    2    9   24   11   11    6    2  779    7   22
8   13   13   26   39   19   37   14    5  601   26
9    8    3    9   19   46   16    4   27   19  683

In [12]:
from sklearn.metrics import recall_score, precision_score, f1_score

In [13]:
precision_score(y_test, y_pred1, average=None)

array([0.94844125, 0.95422177, 0.91411043, 0.90295858, 0.93379791,
       0.8739255 , 0.93262411, 0.91235955, 0.86318408, 0.89320388])

In [15]:
recall_score(y_test, y_pred1, average=None)

array([0.9634592 , 0.97505198, 0.8986731 , 0.88310185, 0.93925234,
       0.83676269, 0.94040524, 0.930126  , 0.87515763, 0.882494  ])

In [16]:
precision_score(y_test, y_pred1, average='macro')

0.9128827064397905

In [17]:
precision_score(y_test, y_pred1, average='weighted')

0.9142150713630827

In [19]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred1))

              precision    recall  f1-score   support

           0       0.95      0.96      0.96       821
           1       0.95      0.98      0.96       962
           2       0.91      0.90      0.91       829
           3       0.90      0.88      0.89       864
           4       0.93      0.94      0.94       856
           5       0.87      0.84      0.85       729
           6       0.93      0.94      0.94       839
           7       0.91      0.93      0.92       873
           8       0.86      0.88      0.87       793
           9       0.89      0.88      0.89       834

    accuracy                           0.91      8400
   macro avg       0.91      0.91      0.91      8400
weighted avg       0.91      0.91      0.91      8400