In [2]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv("heart.csv")
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['target'], axis=1), df['target'], test_size=0.2, random_state=2)

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

clf1.fit(X_train, y_train)
clf2.fit(X_train, y_train)

pred1 = clf1.predict(X_test)
pred2 = clf2.predict(X_test)

c:\Users\SUNIL\Anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [6]:
from sklearn.metrics import accuracy_score
print(f'Accuracy of {clf1.__class__.__name__}: {accuracy_score(y_test, pred1)}')
print(f'Accuracy of {clf2.__class__.__name__}: {accuracy_score(y_test, pred2)}')

Accuracy of LogisticRegression: 0.9016393442622951
Accuracy of DecisionTreeClassifier: 0.819672131147541

In [7]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred1)*X_test.shape[0]/100

array([[15.86,  3.66],
       [ 0.  , 17.69]])

In [8]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test, pred1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix

    0   1
0  26   6
1   0  29

In [9]:

print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test, pred2),columns=list(range(0,2)))

Decision Tree Confusion Matrix

    0   1
0  24   8
1   3  26

In [10]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = pred1
result['Decision Tree Prediction'] = pred2

In [11]:
result.sample(10)

     Actual Label  Logistic Regression Prediction  Decision Tree Prediction
234             0                               0                         0
179             0                               0                         0
157             1                               1                         1
140             1                               1                         1
94              1                               1                         1
274             0                               0                         0
276             0                               0                         0
182             0                               1                         1
173             0                               0                         1
169             0                               0                         0

In [12]:
from sklearn.metrics import precision_score, recall_score, f1_score

In [15]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,pred1))
print("Recall - ",recall_score(y_test,pred1))
print("F1 score - ",f1_score(y_test,pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  26   6
1   0  29
--------------------------------------------------
Precision -  0.8285714285714286
Recall -  1.0
F1 score -  0.90625

In [16]:

print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,pred2))
print("Recall - ",recall_score(y_test,pred2))
print("F1 score - ",f1_score(y_test,pred2))

For DT Model
--------------------------------------------------
    0   1
0  24   8
1   3  26
--------------------------------------------------
Precision -  0.7647058823529411
Recall -  0.896551724137931
F1 score -  0.8253968253968254

In [17]:
precision_score(y_test, pred1,average=None)

array([1.        , 0.82857143])

In [ ]:
precision_score(y_test, pred2 ,average=None)

array([0.88888889, 0.76470588])

In [19]:

recall_score(y_test, pred1 ,average=None)

array([0.8125, 1.    ])

In [20]:
recall_score(y_test, pred2, average=None)

array([0.75      , 0.89655172])

In [13]:
from sklearn.metrics import classification_report
print(classification_report(y_test, pred1))

              precision    recall  f1-score   support

           0       1.00      0.81      0.90        32
           1       0.83      1.00      0.91        29

    accuracy                           0.90        61
   macro avg       0.91      0.91      0.90        61
weighted avg       0.92      0.90      0.90        61